version: '3.8'

services:
    db:
      image: 'postgres:latest'
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - 5432
      networks:
        - test
    web:
      build: ./el/
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - ./el:/code
      ports:
        - 8000:8000
      depends_on:
        - db
      links:
        - db:db
      networks:
        - test
    app:
      container_name: frontend
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - '.:/frontend'
        - '/frontend/node_modules'
      ports:
        - 4000:4000
      depends_on:
        - web
      networks:
        - test
networks:
  test:
      driver: bridge